# AeroSpace config
# https://nikitabobko.github.io/AeroSpace/guide

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

default-root-container-layout = 'accordion'

[mode.main.binding]

# alt-cmd-ctrl is a key remapped via the HyperKey app (see home/keyboard config)

alt-cmd-ctrl-tab = 'focus right --boundaries-action wrap-around-the-workspace --ignore-floating'

alt-cmd-ctrl-h = 'focus left'
alt-cmd-ctrl-left = 'focus left'
alt-cmd-ctrl-l = 'focus right'
alt-cmd-ctrl-right = 'focus right'

alt-cmd-ctrl-r = ['reload-config', 'layout h_accordion']
alt-cmd-ctrl-t = ['layout h_tiles']

alt-cmd-ctrl-shift-left = 'move left'
alt-cmd-ctrl-shift-right = 'move right'

alt-cmd-ctrl-1 = ['workspace 1', 'layout h_accordion']
alt-cmd-ctrl-2 = ['workspace 2', 'layout h_accordion']
alt-cmd-ctrl-3 = ['workspace 3', 'layout h_accordion']
alt-cmd-ctrl-4 = ['workspace 4', 'layout h_accordion']
alt-cmd-ctrl-5 = ['workspace 5', 'layout h_accordion']
alt-cmd-ctrl-6 = ['workspace 6', 'layout h_accordion']
alt-cmd-ctrl-7 = ['workspace 7', 'layout h_accordion']
alt-cmd-ctrl-8 = ['workspace 8', 'layout h_accordion']
alt-cmd-ctrl-9 = ['workspace 9', 'layout h_accordion']
alt-cmd-ctrl-0 = ['workspace 10', 'layout h_accordion']

alt-cmd-ctrl-shift-1 = [
    'move-node-to-workspace 1',
    'workspace 1',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-2 = [
    'move-node-to-workspace 2',
    'workspace 2',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-3 = [
    'move-node-to-workspace 3',
    'workspace 3',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-4 = [
    'move-node-to-workspace 4',
    'workspace 4',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-5 = [
    'move-node-to-workspace 5',
    'workspace 5',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-6 = [
    'move-node-to-workspace 6',
    'workspace 6',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-7 = [
    'move-node-to-workspace 7',
    'workspace 7',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-8 = [
    'move-node-to-workspace 8',
    'workspace 8',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-9 = [
    'move-node-to-workspace 9',
    'workspace 9',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-0 = [
    'move-node-to-workspace 10',
    'workspace 10',
    'layout h_accordion',
]

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'secondary'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
run = 'move-node-to-workspace 2'
[[on-window-detected]]
if.app-name-regex-substring = 'Zen'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'Webstorm'
run = 'move-node-to-workspace 3'
[[on-window-detected]]
if.app-name-regex-substring = 'Cursor'
run = 'move-node-to-workspace 3'
[[on-window-detected]]
if.app-name-regex-substring = 'Zed'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace 4'
[[on-window-detected]]
if.app-name-regex-substring = 'Signal'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chrome'
run = 'move-node-to-workspace 5'
[[on-window-detected]]
if.app-name-regex-substring = 'Spotify'
run = 'move-node-to-workspace 5'
