# AeroSpace config
# https://nikitabobko.github.io/AeroSpace/guide

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

default-root-container-layout = 'accordion'

[mode.main.binding]
# cmd-enter = '''exec-and-forget osascript -e '
#       tell application "Terminal"
#           do script
#           activate
#       end tell'
#       '''

# cmd-h = 'focus left'
# cmd-j = 'focus down'
# cmd-k = 'focus up'
# cmd-l = 'focus right'
#
# cmd-shift-h = 'move left'
# cmd-shift-j = 'move down'
# cmd-shift-k = 'move up'
# cmd-shift-l = 'move right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'secondary'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'Webstorm'
run = 'move-node-to-workspace 3'
[[on-window-detected]]
if.app-name-regex-substring = 'Cursor'
run = 'move-node-to-workspace 3'
[[on-window-detected]]
if.app-name-regex-substring = 'Zed'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chrome'
run = 'move-node-to-workspace 5'
